# Generated by Django 3.2.4 on 2021-07-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_name_course_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='language',
            new_name='description',
        ),
    ]
