# Generated by Django 3.2.4 on 2021-07-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_language_course_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Restaurant',
        ),
    ]
